### PR TITLE
Add Android hook HOC

### PR DESCRIPTION
**Pull request by fsih**
Adds functions to send and receive costume and sprite library requests to Android, to allow us to have native libraries

This change works toward fixing #67

### CODE REVIEW

**Comment by fsih** [comment]
@paulkaplan @chrisgarrity I can't set reviewers

**Review by rschamp — CHANGES_REQUESTED** [review]
From our 🏖 conversation:

Update the `onNew*Click`'s to call a prop passed into the top-level GUI container.
Also update these handlers to expect an `onDone` function argument (see @paulkaplan for the rest of the explanation of this one)

**Comment by fsih** [comment]
Pull into develop instead of paulkaplan/native

**Comment by fsih** [comment]
Closing since we're using Paul's implementation

**Pull request closed without merging**
